sudo: required
services:
  - docker

before_install:
  - docker build -t fabianthorsen/react-test -f ./client/dev.Dockerfile ./client

script:
  - docker run -e CI=true fabianthorsen/react-test npm test

after_success:
  # Build all images
  - docker build -t fabianthorsen/multi-client ./client
  - docker build -t fabianthorsen/multi-nginx ./nginx
  - docker build -t fabianthorsen/multi-server ./server
  - docker build -t fabianthorsen/multi-worker ./worker
  # Login to docker-cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take these images and push to docker hub
  - docker push fabianthorsen/multi-client
  - docker push fabianthorsen/multi-nginx
  - docker push fabianthorsen/multi-server
  - docker push fabianthorsen/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "Multidocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-454363662143"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
